### PR TITLE
Helper method to load data into sheet

### PR DESCRIPTION
**Pull request by mguinness**
This helper method is useful when you want to load data into a sheet from an LINQ query with EF.

```
var ws = new Worksheet("Sheet1");
ws.Populate(ctx.Orders.Where(o => o.Type == "Phone"));
```

I added it to the Worksheet class in case others might find it useful as it would be a common use case.

### CODE REVIEW

**Comment by mstum** [comment]
Thank you, I'll look at this and your comments in a bit.

**Comment by mguinness** [comment]
@mstum Would you be able to review this week?  I'm hoping that since this is a new method it should have no impact on current usage.  Thanks.

**Comment by mstum** [comment]
I committed this as fecbc1bb797650490c55bf944bec8eeb95c50222

I added a null check and ToListed the Object Properties, since it's enumerated twice. There are a few caveats, but this is a useful method, thanks!

I'm currently setting up a new build server to look at #15 for a Simplexcel 3.0 release.

**Comment by mguinness** [comment]
@mstum In lieu of version 3.0, would it be possible to publish version 2.0.2 to NuGet that includes this PR?

**Comment by mstum** [comment]
Hi, yeah, I'll get a release out this evening. Sorry for the slow response, been really busy with a work project and will be for a bit more, but I'll get that pushed out to Nuget today.

**Comment by mguinness** [comment]
Appreciate that, thanks for making the time.

**Comment by mstum** [comment]
Version 2.0.3.6 should now be live, might be a bit until Nuget picks up the change though. https://www.nuget.org/packages/simplexcel/2.0.3.6

**Comment by mguinness** [comment]
Thank you, also the FromData static method is a nice addition!

**Pull request closed without merging**
